{
    "osv": {
        "package": {
            "name": "python2.2"
        },
        "published": "2004-10-10",
        "references": [
            {
                "type": "DSA",
                "url": "https://www.debian.org/security/2004/dsa-458"
            }
        ]
    },
    "uvi": {
        "experimental": {
            "advisory_type": "DSA-458-3",
            "other_identifiers": {
                "cve": [
                    "CVE-2004-0150"
                ]
            },
            "package_affected": [
                {
                    "distribution_affected": "woody",
                    "fixed in": "For the stable distribution (woody), this bug has been fixed in version 2.2.1-4.6"
                }
            ],
            "package_name": "python2.2",
            "processed_timestamp": "2021-07-18T03:08:09.605523Z",
            "uvi_script_name": "./www.debian.org-processing.py",
            "uvi_script_version": "0.0.5",
            "vulnerability_status": "yes"
        },
        "product_name": "Linux",
        "vendor_name": "Debian"
    }
}