{
    "error": "HTTPSConnectionPool(host='bugzilla.fedora.us', port=443): Max retries exceeded with url: /show_bug.cgi?id=1944 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01d3af7940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}