{
    "osv": {
        "package": {
            "name": "python-django"
        },
        "published": "2016-04-07",
        "references": [
            {
                "type": "DSA",
                "url": "https://www.debian.org/security/2016/dsa-3544"
            }
        ]
    },
    "uvi": {
        "experimental": {
            "advisory_type": "DSA-3544-1",
            "other_identifiers": {
                "cve": [
                    "CVE-2016-2512",
                    "CVE-2016-2513"
                ]
            },
            "package_affected": [
                {
                    "distribution_affected": "wheezy",
                    "fixed in": "1.4.5-1+deb7u16"
                },
                {
                    "distribution_affected": "jessie",
                    "fixed in": "1.7.7-1+deb8u4"
                },
                {
                    "distribution_affected": "stretch",
                    "fixed in": "1.9.4-1"
                },
                {
                    "distribution_affected": "sid",
                    "fixed in": "1.9.4-1"
                }
            ],
            "package_name": "python-django",
            "processed_timestamp": "2021-07-18T03:09:05.153579Z",
            "uvi_script_name": "./www.debian.org-processing.py",
            "uvi_script_version": "0.0.5",
            "vulnerability_status": "yes"
        },
        "product_name": "Linux",
        "vendor_name": "Debian"
    }
}