<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
<link rel="icon" href="/favicon.png">
<title>#850716 - python-pysaml2: CVE-2016-10149 - Debian Bug report logs</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/css/bugs.css" type="text/css">

<link rel="canonical" href="&lt;a href=&quot;bugreport.cgi?bug=850716&quot;&gt;850716&lt;/a&gt;">
<script type="text/javascript">
<!--
function toggle_infmessages()
{
        allDivs=document.getElementsByTagName("div");
        for (var i = 0 ; i < allDivs.length ; i++ )
        {
                if (allDivs[i].className == "infmessage")
                {
                        allDivs[i].style.display=(allDivs[i].style.display == 'none' | allDivs[i].style.display == '') ? 'block' : 'none';
                }
        }
}
-->
</script>
</head>
<body>
<h1>Debian Bug report logs - 
<a href="mailto:850716@bugs.debian.org">#850716</a><br>
python-pysaml2: CVE-2016-10149</h1>
<div class="versiongraph"><a href="version.cgi?info=1;found=python-pysaml2%2F2.0.0-1;absolute=0;collapse=1;package=src%3Apython-pysaml2;fixed=python-pysaml2%2F3.0.0-5;fixed=python-pysaml2%2F2.0.0-1%2Bdeb8u1"><img alt="version graph" src="version.cgi?found=python-pysaml2%2F2.0.0-1;absolute=0;height=2;collapse=1;width=2;fixed=python-pysaml2%2F3.0.0-5;fixed=python-pysaml2%2F2.0.0-1%2Bdeb8u1;package=src%3Apython-pysaml2"></a></div>
<div class="pkginfo">
  <p>Package:
     <a class="submitter" href="pkgreport.cgi?src=python-pysaml2">src:python-pysaml2</a>;
Maintainer for <a href="pkgreport.cgi?src=python-pysaml2">src:python-pysaml2</a> is <a href="pkgreport.cgi?maint=team%2Bopenstack%40tracker.debian.org">Debian OpenStack &lt;team+openstack@tracker.debian.org&gt;</a>; </p>

</div>

<div class="buginfo">
  <p>Reported by: <a href="pkgreport.cgi?submitter=zigo%40debian.org">Thomas Goirand &lt;zigo@debian.org&gt;</a></p>
  <p>Date: Mon,  9 Jan 2017 15:30:05 UTC</p>

<p>Severity: <em class="severity">serious</em></p>
<p>Tags: patch, security, upstream</p>

<p>Found in version python-pysaml2/2.0.0-1</p>
<p>Fixed in versions python-pysaml2/3.0.0-5, python-pysaml2/2.0.0-1+deb8u1</p>

<p><strong>Done:</strong> Thomas Goirand &lt;zigo@debian.org&gt;</p>

<p>Bug is archived. No further changes may be made.<p><p>Forwarded to <a href="https://github.com/rohe/pysaml2/pull/379">https://github.com/rohe/pysaml2/pull/379</a></p>
</div>

<p><a href="javascript:toggle_infmessages();">Toggle useless messages</a></p><div class="msgreceived"><p>View this report as an <a href="bugreport.cgi?bug=850716;mbox=yes">mbox folder</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;mboxstatus=yes">status mbox</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;mboxmaint=yes">maintainer mbox</a></p></div>

<div class="infmessage"><hr><p>
<a name="1"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, team@security.debian.org, secure-testing-team@lists.alioth.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt; -->
<!-- time:1483975807 -->
<strong>Report forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, team@security.debian.org, secure-testing-team@lists.alioth.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>:<br>
<code>Bug#850716</code>; Package <code>src:python-pysaml2</code>.
 (Mon, 09 Jan 2017 15:30:07 GMT) (<a href="bugreport.cgi?bug=850716;msg=2">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=2">mbox</a>, <a href="#1">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="3"></a>
<!-- request_addr: Thomas Goirand &lt;zigo@debian.org&gt; -->
<!-- time:1483975807 -->
<strong>Acknowledgement sent</strong>
to <code>Thomas Goirand &lt;zigo@debian.org&gt;</code>:<br>
New Bug report received and forwarded.  Copy sent to <code>team@security.debian.org, secure-testing-team@lists.alioth.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>.
 (Mon, 09 Jan 2017 15:30:07 GMT) (<a href="bugreport.cgi?bug=850716;msg=4">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=4">mbox</a>, <a href="#3">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="5"></a><a name="msg5"></a><a href="#5">Message #5</a> received at submit@bugs.debian.org (<a href="bugreport.cgi?bug=850716;msg=5">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=5">mbox</a>, <a href="mailto:850716@bugs.debian.org?In-Reply-To=%3C20170109152840.16451.84741.reportbug%40buzig2.mirantis.com%3E&amp;References=%3C20170109152840.16451.84741.reportbug%40buzig2.mirantis.com%3E&amp;body=On%20Mon%2C%2009%20Jan%202017%2016%3A28%3A40%20%2B0100%20Thomas%20Goirand%20%3Czigo%40debian.org%3E%20wrote%3A%0A%3E%20Source%3A%20python-pysaml2%0A%3E%20Severity%3A%20serious%0A%3E%20Tags%3A%20security%20patch%0A%3E%20%0A%3E%20As%20per%20report%20from%20user%3A%0A%3E%20%0A%3E%20--------%20Forwarded%20Message%20--------%0A%3E%20Subject%3A%20python-pysaml2%20XEE%20vulnerability%0A%3E%20Date%3A%20Mon%2C%209%20Jan%202017%2014%3A50%3A41%20%2B0100%0A%3E%20From%3A%20Florian%20Best%20%3Cbest%40univention.de%3E%0A%3E%20Organization%3A%20Univention%20GmbH%0A%3E%20To%3A%20zigo%40debian.org%0A%3E%20CC%3A%20openstack-devel%40lists.alioth.debian.org%0A%3E%20%0A%3E%20Dear%20debian%20python-pysaml2%20maintainers%2C%0A%3E%20%0A%3E%20there%20was%20a%20security%20hole%20fixed%20in%20python-pysaml2%2C%20which%20allowed%20XML%0A%3E%20External%20Entity%20attacks%3A%0A%3E%20https%3A%2F%2Fgithub.com%2Frohe%2Fpysaml2%2Fpull%2F379%0A%3E%20https%3A%2F%2Fgithub.com%2Frohe%2Fpysaml2%2Fcommit%2F6e09a25d9b4b7aa7a506853210a9a14100b8bc9b%0A%3E%20%0A%3E%20Could%20you%20please%20release%20a%20security%20update%3F%0A%3E%20%0A%3E%20Best%20regards%2C%0A%3E%20Florian%0A%3E%20%0A%3E%20%0A&amp;subject=Re%3A%20XML%20External%20Entity%20attack">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=zigo%40debian.org" alt="">
<div class="header"><span class="headerfield">From:</span> Thomas Goirand &lt;zigo@debian.org&gt;</div>
<div class="header"><span class="headerfield">To:</span> Debian Bug Tracking System &lt;submit@bugs.debian.org&gt;</div>
<div class="header"><span class="headerfield">Subject:</span> XML External Entity attack</div>
<div class="header"><span class="headerfield">Date:</span> Mon, 09 Jan 2017 16:28:40 +0100</div>
</div>
<pre class="message">Source: python-pysaml2
Severity: serious
Tags: security patch

As per report from user:

-------- Forwarded Message --------
Subject: python-pysaml2 XEE vulnerability
Date: Mon, 9 Jan 2017 14:50:41 +0100
From: Florian Best &lt;best@univention.de&gt;
Organization: Univention GmbH
To: zigo@debian.org
CC: openstack-devel@lists.alioth.debian.org

Dear debian python-pysaml2 maintainers,

there was a security hole fixed in python-pysaml2, which allowed XML
External Entity attacks:
<a href="https://github.com/rohe/pysaml2/pull/379">https://github.com/rohe/pysaml2/pull/379</a>
<a href="https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b">https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b</a>

Could you please release a security update?

Best regards,
Florian


</pre>

<div class="msgreceived"><hr><p>
<a name="6"></a>
<!-- command:forwarded -->
<!-- requester: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- request_addr: control@bugs.debian.org -->
<!-- time:1483980304 -->
<!-- new_data:
$new_data = {
              &#39;forwarded&#39; =&gt; &#39;<a href="https://github.com/rohe/pysaml2/pull/379">https://github.com/rohe/pysaml2/pull/379</a>&#39;
            };
-->
<!-- old_data:
$old_data = {
              &#39;forwarded&#39; =&gt; &#39;&#39;
            };
-->
<strong>Set Bug forwarded-to-address to &#39;<a href="https://github.com/rohe/pysaml2/pull/379">https://github.com/rohe/pysaml2/pull/379</a>&#39;.</strong>
Request was from <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>
to <code>control@bugs.debian.org</code>.
 (Mon, 09 Jan 2017 16:45:04 GMT) (<a href="bugreport.cgi?bug=850716;msg=7">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=7">mbox</a>, <a href="#6">link</a>).</p></p></div>

<div class="msgreceived"><hr><p>
<a name="8"></a>
<!-- command:tag -->
<!-- requester: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- request_addr: control@bugs.debian.org -->
<!-- time:1483980304 -->
<!-- new_data:
$new_data = {
              &#39;keywords&#39; =&gt; &#39;security upstream patch&#39;
            };
-->
<!-- old_data:
$old_data = {
              &#39;keywords&#39; =&gt; &#39;patch security&#39;
            };
-->
<strong>Added tag(s) upstream.</strong>
Request was from <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>
to <code>control@bugs.debian.org</code>.
 (Mon, 09 Jan 2017 16:45:04 GMT) (<a href="bugreport.cgi?bug=850716;msg=9">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=9">mbox</a>, <a href="#8">link</a>).</p></p></div>

<div class="msgreceived"><hr><p>
<a name="10"></a>
<!-- command:found -->
<!-- requester: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- request_addr: control@bugs.debian.org -->
<!-- time:1483980305 -->
<!-- new_data:
$new_data = {
              &#39;found_versions&#39; =&gt; [
                                    &#39;python-pysaml2/2.0.0-1&#39;
                                  ]
            };
-->
<!-- old_data:
$old_data = {
              &#39;found_versions&#39; =&gt; []
            };
-->
<strong>Marked as found in versions python-pysaml2/2.0.0-1.</strong>
Request was from <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>
to <code>control@bugs.debian.org</code>.
 (Mon, 09 Jan 2017 16:45:05 GMT) (<a href="bugreport.cgi?bug=850716;msg=11">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=11">mbox</a>, <a href="#10">link</a>).</p></p></div>

<div class="msgreceived"><hr><p>
<a name="12"></a>
<!-- request_addr: Thomas Goirand &lt;zigo@debian.org&gt; -->
<!-- time:1483996870 -->
<strong>Reply sent</strong>
to <code>Thomas Goirand &lt;zigo@debian.org&gt;</code>:<br>
You have taken responsibility.
 (Mon, 09 Jan 2017 21:21:10 GMT) (<a href="bugreport.cgi?bug=850716;msg=13">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=13">mbox</a>, <a href="#12">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="14"></a>
<!-- request_addr: Thomas Goirand &lt;zigo@debian.org&gt; -->
<!-- time:1483996870 -->
<strong>Notification sent</strong>
to <code>Thomas Goirand &lt;zigo@debian.org&gt;</code>:<br>
Bug acknowledged by developer.
 (Mon, 09 Jan 2017 21:21:10 GMT) (<a href="bugreport.cgi?bug=850716;msg=15">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=15">mbox</a>, <a href="#14">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="16"></a><a name="msg16"></a><a href="#16">Message #16</a> received at 850716-close@bugs.debian.org (<a href="bugreport.cgi?bug=850716;msg=16">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=16">mbox</a>, <a href="mailto:850716@bugs.debian.org?subject=Re%3A%20Bug%23850716%3A%20fixed%20in%20python-pysaml2%203.0.0-5&amp;References=%3CE1cQhL5-00008S-Dh%40fasolo.debian.org%3E&amp;body=On%20Mon%2C%2009%20Jan%202017%2021%3A18%3A47%20%2B0000%20Thomas%20Goirand%20%3Czigo%40debian.org%3E%20wrote%3A%0A%3E%20Source%3A%20python-pysaml2%0A%3E%20Source-Version%3A%203.0.0-5%0A%3E%20%0A%3E%20We%20believe%20that%20the%20bug%20you%20reported%20is%20fixed%20in%20the%20latest%20version%20of%0A%3E%20python-pysaml2%2C%20which%20is%20due%20to%20be%20installed%20in%20the%20Debian%20FTP%20archive.%0A%3E%20%0A%3E%20A%20summary%20of%20the%20changes%20between%20this%20version%20and%20the%20previous%20one%20is%0A%3E%20attached.%0A%3E%20%0A%3E%20Thank%20you%20for%20reporting%20the%20bug%2C%20which%20will%20now%20be%20closed.%20%20If%20you%0A%3E%20have%20further%20comments%20please%20address%20them%20to%20850716%40bugs.debian.org%2C%0A%3E%20and%20the%20maintainer%20will%20reopen%20the%20bug%20report%20if%20appropriate.%0A%3E%20%0A%3E%20Debian%20distribution%20maintenance%20software%0A%3E%20pp.%0A%3E%20Thomas%20Goirand%20%3Czigo%40debian.org%3E%20%28supplier%20of%20updated%20python-pysaml2%20package%29%0A%3E%20%0A%3E%20%28This%20message%20was%20generated%20automatically%20at%20their%20request%3B%20if%20you%0A%3E%20believe%20that%20there%20is%20a%20problem%20with%20it%20please%20contact%20the%20archive%0A%3E%20administrators%20by%20mailing%20ftpmaster%40ftp-master.debian.org%29%0A%3E%20%0A%3E%20%0A%3E%20-----BEGIN%20PGP%20SIGNED%20MESSAGE-----%0A%3E%20Hash%3A%20SHA256%0A%3E%20%0A%3E%20Format%3A%201.8%0A%3E%20Date%3A%20Mon%2C%2009%20Jan%202017%2016%3A28%3A55%20%2B0100%0A%3E%20Source%3A%20python-pysaml2%0A%3E%20Binary%3A%20python-pysaml2%20python3-pysaml2%20python-pysaml2-doc%0A%3E%20Architecture%3A%20source%20all%0A%3E%20Version%3A%203.0.0-5%0A%3E%20Distribution%3A%20unstable%0A%3E%20Urgency%3A%20medium%0A%3E%20Maintainer%3A%20PKG%20OpenStack%20%3Copenstack-devel%40lists.alioth.debian.org%3E%0A%3E%20Changed-By%3A%20Thomas%20Goirand%20%3Czigo%40debian.org%3E%0A%3E%20Description%3A%0A%3E%20%20python-pysaml2%20-%20SAML%20Version%202%20to%20be%20used%20in%20a%20WSGI%20environment%20-%20Python%202.x%0A%3E%20%20python-pysaml2-doc%20-%20SAML%20Version%202%20to%20be%20used%20in%20a%20WSGI%20environment%20-%20doc%0A%3E%20%20python3-pysaml2%20-%20SAML%20Version%202%20to%20be%20used%20in%20a%20WSGI%20environment%20-%20Python%203.x%0A%3E%20Closes%3A%20850716%0A%3E%20Changes%3A%0A%3E%20%20python-pysaml2%20%283.0.0-5%29%20unstable%3B%20urgency%3Dmedium%0A%3E%20%20.%0A%3E%20%20%20%20%5B%20Ond%C5%99ej%20Nov%C3%BD%20%5D%0A%3E%20%20%20%20%2A%20Bumped%20debhelper%20compat%20version%20to%2010%0A%3E%20%20.%0A%3E%20%20%20%20%5B%20Thomas%20Goirand%20%5D%0A%3E%20%20%20%20%2A%20Add%20upstream%20patch%20for%20XML%20External%20Entity%20attack%20%28Closes%3A%20%23850716%29.%0A%3E%20Checksums-Sha1%3A%0A%3E%20%2026ddbadcba3e2f25dfb6ea80f407e324b58f2172%202819%20python-pysaml2_3.0.0-5.dsc%0A%3E%20%203b55888eeb75408b72e2765195a6b8f0d430ec1f%206820%20python-pysaml2_3.0.0-5.debian.tar.xz%0A%3E%20%20e200a13ef2d6e661f0d842ac4d07f2b32ce9e421%2047662%20python-pysaml2-doc_3.0.0-5_all.deb%0A%3E%20%2034dc5af2177f5163a2ea5a35f5e629d10e7171d3%20194944%20python-pysaml2_3.0.0-5_all.deb%0A%3E%20%2058c3c49d3af4e37f1654fb24022c942a790affd8%208545%20python-pysaml2_3.0.0-5_amd64.buildinfo%0A%3E%20%2046eb2bea8895521820aeb601b3acdebcd43fce85%20195004%20python3-pysaml2_3.0.0-5_all.deb%0A%3E%20Checksums-Sha256%3A%0A%3E%20%20c5e1cb13bbc0b128668a103bd0771355d2e84ef3af132dbd745f62c9b419c5c2%202819%20python-pysaml2_3.0.0-5.dsc%0A%3E%20%20127eaf74e6ead92af2a526e5b3aceadff3be6124cacdbd29745726fa0e10e779%206820%20python-pysaml2_3.0.0-5.debian.tar.xz%0A%3E%20%207586bf002a940d74a65abea4076f617f9c5090bcb13e1252c541e5c23d2a7954%2047662%20python-pysaml2-doc_3.0.0-5_all.deb%0A%3E%20%20375da92f94f7d5390e5c7e1f389155511fe2e6c404af53769cb4b9ada0409148%20194944%20python-pysaml2_3.0.0-5_all.deb%0A&amp;In-Reply-To=%3CE1cQhL5-00008S-Dh%40fasolo.debian.org%3E">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=zigo%40debian.org" alt="">
<div class="header"><span class="headerfield">From:</span> Thomas Goirand &lt;zigo@debian.org&gt;</div>
<div class="header"><span class="headerfield">To:</span> 850716-close@bugs.debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Bug#850716: fixed in python-pysaml2 3.0.0-5</div>
<div class="header"><span class="headerfield">Date:</span> Mon, 09 Jan 2017 21:18:47 +0000</div>
</div>
<pre class="message">Source: python-pysaml2
Source-Version: 3.0.0-5

We believe that the bug you reported is fixed in the latest version of
python-pysaml2, which is due to be installed in the Debian FTP archive.

A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 850716@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Thomas Goirand &lt;zigo@debian.org&gt; (supplier of updated python-pysaml2 package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@ftp-master.debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Format: 1.8
Date: Mon, 09 Jan 2017 16:28:55 +0100
Source: python-pysaml2
Binary: python-pysaml2 python3-pysaml2 python-pysaml2-doc
Architecture: source all
Version: 3.0.0-5
Distribution: unstable
Urgency: medium
Maintainer: PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;
Changed-By: Thomas Goirand &lt;zigo@debian.org&gt;
Description:
 python-pysaml2 - SAML Version 2 to be used in a WSGI environment - Python 2.x
 python-pysaml2-doc - SAML Version 2 to be used in a WSGI environment - doc
 python3-pysaml2 - SAML Version 2 to be used in a WSGI environment - Python 3.x
Closes: <a href="bugreport.cgi?bug=850716">850716</a>
Changes:
 python-pysaml2 (3.0.0-5) unstable; urgency=medium
 .
   [ Ondřej Nový ]
   * Bumped debhelper compat version to 10
 .
   [ Thomas Goirand ]
   * Add upstream patch for XML External Entity attack (Closes: #<a href="bugreport.cgi?bug=850716">850716</a>).
Checksums-Sha1:
 26ddbadcba3e2f25dfb6ea80f407e324b58f2172 2819 python-pysaml2_3.0.0-5.dsc
 3b55888eeb75408b72e2765195a6b8f0d430ec1f 6820 python-pysaml2_3.0.0-5.debian.tar.xz
 e200a13ef2d6e661f0d842ac4d07f2b32ce9e421 47662 python-pysaml2-doc_3.0.0-5_all.deb
 34dc5af2177f5163a2ea5a35f5e629d10e7171d3 194944 python-pysaml2_3.0.0-5_all.deb
 58c3c49d3af4e37f1654fb24022c942a790affd8 8545 python-pysaml2_3.0.0-5_amd64.buildinfo
 46eb2bea8895521820aeb601b3acdebcd43fce85 195004 python3-pysaml2_3.0.0-5_all.deb
Checksums-Sha256:
 c5e1cb13bbc0b128668a103bd0771355d2e84ef3af132dbd745f62c9b419c5c2 2819 python-pysaml2_3.0.0-5.dsc
 127eaf74e6ead92af2a526e5b3aceadff3be6124cacdbd29745726fa0e10e779 6820 python-pysaml2_3.0.0-5.debian.tar.xz
 7586bf002a940d74a65abea4076f617f9c5090bcb13e1252c541e5c23d2a7954 47662 python-pysaml2-doc_3.0.0-5_all.deb
 375da92f94f7d5390e5c7e1f389155511fe2e6c404af53769cb4b9ada0409148 194944 python-pysaml2_3.0.0-5_all.deb
 6529e2163ec3f704e237ca5441cca03b87c5af3e1ce5823850b73c58f5078443 8545 python-pysaml2_3.0.0-5_amd64.buildinfo
 03bb85bb37a5d810d8198c4fda76fb61237ec97a875f22722b38accebc77cdd3 195004 python3-pysaml2_3.0.0-5_all.deb
Files:
 5c7c052342348d46ec7280d246c697bc 2819 python optional python-pysaml2_3.0.0-5.dsc
 7b3680149b2c11f5ee9f85e8049bf416 6820 python optional python-pysaml2_3.0.0-5.debian.tar.xz
 d0e667aa5605d9d4db5914aef4b66a3c 47662 doc optional python-pysaml2-doc_3.0.0-5_all.deb
 8602ceb1c8a50bb5a2d9bd44c4d00c32 194944 python optional python-pysaml2_3.0.0-5_all.deb
 c559655b278d1541c0269080f90811d6 8545 python optional python-pysaml2_3.0.0-5_amd64.buildinfo
 beb47f23946c91e5d45f11f7f6a02d31 195004 python optional python3-pysaml2_3.0.0-5_all.deb

-----BEGIN PGP SIGNATURE-----

iQJEBAEBCAAuFiEEoLGp81CJVhMOekJc1BatFaxrQ/4FAlhz99kQHHppZ29AZGVi
aWFuLm9yZwAKCRDUFq0VrGtD/lrrEACRTTtT0gpNhjL4BMbXsYaA92k/Od5Hm4v+
DxbimVdb23hvdou4kHJGtWMXistIHXZsamIzz95Fygnk03MaNBA18Rb4b8AE2qQA
flbtgOtacRLKCgrcZmZB8Dgz8FAh1vL6HCEOnEkltWlCkbc0V74d4ryXQ5476sPI
uZuFdm+Akh2mPK9Le/8TMzuCafrCe6Ury6Y8ZXFmdmP5x3a4bUw8synCtgJ8fY2i
VqwVhWyXLFodeOvEmy2rn5mnSP8Y+SXQvT+P4toN0/2o7I2WH30feNakxUK6D43H
U4KQ0lyTMufDKKheQ1DiBdTes5fTZEgJKjPCahHkuseXhpgwvF23iCjxGc/W1tPN
wMj2qXxx26mc6AhtCylrRjvRwYyrZIdoL4ayzJrfnMntKkOBBI1HIAjvaxW3B6aw
IRts5sNG+AjVUQaGSvaZcGO59ed9IPKlFjEQ/bdfcA6mR+QTW4tz6wWPsVfEijTz
oAH4WVm9TGUARPzz8FOSIrlx84AibjDazyG05vgGyzEsLHsLn1Kq1MCNTnaj79kk
g2BMMJO3/NYnXOPnjNj8cr/dTcZfHhl5tButx0D37CoCtjN1CwAztZ782MNV4dWz
nVvV8HByk8A/nZ8Gvo37vf44FZo3pdCuQkij6zBhN9tM1zsTFZZ05QklfuHSgDwe
CfMlm9rYDw==
=tP7f
-----END PGP SIGNATURE-----



</pre>

<div class="infmessage"><hr><p>
<a name="17"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt; -->
<!-- time:1484113145 -->
<strong>Information forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>:<br>
<code>Bug#850716</code>; Package <code>src:python-pysaml2</code>.
 (Wed, 11 Jan 2017 05:39:05 GMT) (<a href="bugreport.cgi?bug=850716;msg=18">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=18">mbox</a>, <a href="#17">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="19"></a>
<!-- request_addr: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- time:1484113145 -->
<strong>Acknowledgement sent</strong>
to <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>:<br>
Extra info received and forwarded to list.  Copy sent to <code>PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>.
 (Wed, 11 Jan 2017 05:39:05 GMT) (<a href="bugreport.cgi?bug=850716;msg=20">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=20">mbox</a>, <a href="#19">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="21"></a><a name="msg21"></a><a href="#21">Message #21</a> received at 850716@bugs.debian.org (<a href="bugreport.cgi?bug=850716;msg=21">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=21">mbox</a>, <a href="mailto:850716@bugs.debian.org?References=%3C20170109152840.16451.84741.reportbug%40buzig2.mirantis.com%3E%0A%20%3C20170111053813.xir77f6tsms54dsc%40lorien.valinor.li%3E&amp;body=On%20Wed%2C%2011%20Jan%202017%2006%3A38%3A13%20%2B0100%20Salvatore%20Bonaccorso%20%3Ccarnil%40debian.org%3E%20wrote%3A%0A%3E%20Control%3A%20retitle%20-1%20python-pysaml2%3A%20CVE-2016-10127%3A%20XML%20External%20Entity%20attack%0A%3E%20%0A%3E%20Hi%0A%3E%20%0A%3E%20This%20issue%20has%20been%20assigned%20CVE-2016-10127%2C%20cf.%0A%3E%20http%3A%2F%2Fwww.openwall.com%2Flists%2Foss-security%2F2017%2F01%2F11%2F5%0A%3E%20%0A%3E%20Regards%2C%0A%3E%20Salvatore%0A%3E%20%0A%3E%20%0A&amp;subject=Re%3A%20Bug%23850716%3A%20XML%20External%20Entity%20attack&amp;In-Reply-To=%3C20170111053813.xir77f6tsms54dsc%40lorien.valinor.li%3E">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=carnil%40debian.org" alt="">
<div class="header"><span class="headerfield">From:</span> Salvatore Bonaccorso &lt;carnil@debian.org&gt;</div>
<div class="header"><span class="headerfield">To:</span> Thomas Goirand &lt;zigo@debian.org&gt;, 850716@bugs.debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Re: Bug#850716: XML External Entity attack</div>
<div class="header"><span class="headerfield">Date:</span> Wed, 11 Jan 2017 06:38:13 +0100</div>
</div>
<pre class="message">Control: retitle -1 python-pysaml2: <a href="https://security-tracker.debian.org/tracker/CVE-2016-10127">CVE-2016-10127</a>: XML External Entity attack

Hi

This issue has been assigned <a href="https://security-tracker.debian.org/tracker/CVE-2016-10127">CVE-2016-10127</a>, cf.
<a href="http://www.openwall.com/lists/oss-security/2017/01/11/5">http://www.openwall.com/lists/oss-security/2017/01/11/5</a>

Regards,
Salvatore


</pre>

<div class="msgreceived"><hr><p>
<a name="22"></a>
<!-- command:title -->
<!-- requester: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- request_addr: 850716-submit@bugs.debian.org -->
<!-- time:1484113145 -->
<!-- new_data:
$new_data = {
              &#39;subject&#39; =&gt; &#39;python-pysaml2: CVE-2016-10127: XML External Entity attack&#39;
            };
-->
<!-- old_data:
$old_data = {
              &#39;subject&#39; =&gt; &#39;XML External Entity attack&#39;
            };
-->
<strong>Changed Bug title to &#39;python-pysaml2: CVE-2016-10127: XML External Entity attack&#39; from &#39;XML External Entity attack&#39;.</strong>
Request was from <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>
to <code>850716-submit@bugs.debian.org</code>.
 (Wed, 11 Jan 2017 05:39:05 GMT) (<a href="bugreport.cgi?bug=850716;msg=23">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=23">mbox</a>, <a href="#22">link</a>).</p></p></div>

<div class="msgreceived"><hr><p>
<a name="24"></a>
<!-- request_addr: Thomas Goirand &lt;zigo@debian.org&gt; -->
<!-- time:1484521584 -->
<strong>Reply sent</strong>
to <code>Thomas Goirand &lt;zigo@debian.org&gt;</code>:<br>
You have taken responsibility.
 (Sun, 15 Jan 2017 23:06:24 GMT) (<a href="bugreport.cgi?bug=850716;msg=25">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=25">mbox</a>, <a href="#24">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="26"></a>
<!-- request_addr: Thomas Goirand &lt;zigo@debian.org&gt; -->
<!-- time:1484521585 -->
<strong>Notification sent</strong>
to <code>Thomas Goirand &lt;zigo@debian.org&gt;</code>:<br>
Bug acknowledged by developer.
 (Sun, 15 Jan 2017 23:06:25 GMT) (<a href="bugreport.cgi?bug=850716;msg=27">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=27">mbox</a>, <a href="#26">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="28"></a><a name="msg28"></a><a href="#28">Message #28</a> received at 850716-close@bugs.debian.org (<a href="bugreport.cgi?bug=850716;msg=28">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=28">mbox</a>, <a href="mailto:850716@bugs.debian.org?In-Reply-To=%3CE1cStp8-000EZa-Hm%40fasolo.debian.org%3E&amp;subject=Re%3A%20Bug%23850716%3A%20fixed%20in%20python-pysaml2%202.0.0-1%2Bdeb8u1&amp;References=%3CE1cStp8-000EZa-Hm%40fasolo.debian.org%3E&amp;body=On%20Sun%2C%2015%20Jan%202017%2023%3A02%3A54%20%2B0000%20Thomas%20Goirand%20%3Czigo%40debian.org%3E%20wrote%3A%0A%3E%20Source%3A%20python-pysaml2%0A%3E%20Source-Version%3A%202.0.0-1%2Bdeb8u1%0A%3E%20%0A%3E%20We%20believe%20that%20the%20bug%20you%20reported%20is%20fixed%20in%20the%20latest%20version%20of%0A%3E%20python-pysaml2%2C%20which%20is%20due%20to%20be%20installed%20in%20the%20Debian%20FTP%20archive.%0A%3E%20%0A%3E%20A%20summary%20of%20the%20changes%20between%20this%20version%20and%20the%20previous%20one%20is%0A%3E%20attached.%0A%3E%20%0A%3E%20Thank%20you%20for%20reporting%20the%20bug%2C%20which%20will%20now%20be%20closed.%20%20If%20you%0A%3E%20have%20further%20comments%20please%20address%20them%20to%20850716%40bugs.debian.org%2C%0A%3E%20and%20the%20maintainer%20will%20reopen%20the%20bug%20report%20if%20appropriate.%0A%3E%20%0A%3E%20Debian%20distribution%20maintenance%20software%0A%3E%20pp.%0A%3E%20Thomas%20Goirand%20%3Czigo%40debian.org%3E%20%28supplier%20of%20updated%20python-pysaml2%20package%29%0A%3E%20%0A%3E%20%28This%20message%20was%20generated%20automatically%20at%20their%20request%3B%20if%20you%0A%3E%20believe%20that%20there%20is%20a%20problem%20with%20it%20please%20contact%20the%20archive%0A%3E%20administrators%20by%20mailing%20ftpmaster%40ftp-master.debian.org%29%0A%3E%20%0A%3E%20%0A%3E%20-----BEGIN%20PGP%20SIGNED%20MESSAGE-----%0A%3E%20Hash%3A%20SHA256%0A%3E%20%0A%3E%20Format%3A%201.8%0A%3E%20Date%3A%20Mon%2C%2009%20Jan%202017%2016%3A54%3A24%20%2B0100%0A%3E%20Source%3A%20python-pysaml2%0A%3E%20Binary%3A%20python-pysaml2%20python-pysaml2-doc%0A%3E%20Architecture%3A%20source%20all%0A%3E%20Version%3A%202.0.0-1%2Bdeb8u1%0A%3E%20Distribution%3A%20jessie-security%0A%3E%20Urgency%3A%20medium%0A%3E%20Maintainer%3A%20PKG%20OpenStack%20%3Copenstack-devel%40lists.alioth.debian.org%3E%0A%3E%20Changed-By%3A%20Thomas%20Goirand%20%3Czigo%40debian.org%3E%0A%3E%20Description%3A%0A%3E%20%20python-pysaml2%20-%20SAML%20Version%202%20to%20be%20used%20in%20a%20WSGI%20environment%20-%20Python%202.x%0A%3E%20%20python-pysaml2-doc%20-%20SAML%20Version%202%20to%20be%20used%20in%20a%20WSGI%20environment%20-%20doc%0A%3E%20Closes%3A%20850716%0A%3E%20Changes%3A%0A%3E%20%20python-pysaml2%20%282.0.0-1%2Bdeb8u1%29%20jessie-security%3B%20urgency%3Dmedium%0A%3E%20%20.%0A%3E%20%20%20%20%2A%20Fix%20XXE%20issues%20on%20anything%20where%20pysaml2%20parses%20XML%20directly%3A%0A%3E%20%20%20%20%20%20-%20CVE-2016-10127%3A%20backporting%20upstream%20patch%20%28Closes%3A%20%23850716%29.%0A%3E%20%20%20%20%20%20-%20add%20python-defusedxml%20as%20runtime%20depends.%0A%3E%20%20%20%20%20%20-%20switch%20debian%2Fgbp.conf%20to%20use%20debian%2Fjessie%20as%20packaging%20branch.%0A%3E%20%20%20%20%2A%20Add%20python-pymongo%20as%20%28build-%29depends.%0A%3E%20Checksums-Sha1%3A%0A%3E%20%200bbf1194d95c45f1fdd9c20cfb5ced27812a404a%202383%20python-pysaml2_2.0.0-1%2Bdeb8u1.dsc%0A%3E%20%20f1fe1d6a295686640b147519711577b328c9d17a%202615832%20python-pysaml2_2.0.0.orig.tar.xz%0A%3E%20%20fe368731d7f97ebbb0be245d1320ae52137e399c%205944%20python-pysaml2_2.0.0-1%2Bdeb8u1.debian.tar.xz%0A%3E%20%20ff1a794513f23be464e3cc2f5badf82ee46a0259%20176868%20python-pysaml2_2.0.0-1%2Bdeb8u1_all.deb%0A%3E%20%2025b6b3d497909f8b68d300dd939b4621ae0618ea%2037866%20python-pysaml2-doc_2.0.0-1%2Bdeb8u1_all.deb%0A%3E%20Checksums-Sha256%3A%0A%3E%20%20651009543559ba6fff0dc051bb717f69f717255a9eaa259dc57584f6dcbcee50%202383%20python-pysaml2_2.0.0-1%2Bdeb8u1.dsc%0A%3E%20%20c62d179ba27d345d9159d9a3f2bddea7567973720cbf916bbd05eda3e18e935f%202615832%20python-pysaml2_2.0.0.orig.tar.xz%0A%3E%20%2078209ca2e4ee6c6fd00a0c735646f668f1e5d0187d98c120c49a821ac20375c7%205944%20python-pysaml2_2.0.0-1%2Bdeb8u1.debian.tar.xz%0A%3E%20%203e85114f08d18f3c64ca2b9d6703de44c2655298c6262701665ad1790f47784a%20176868%20python-pysaml2_2.0.0-1%2Bdeb8u1_all.deb%0A%3E%20%20b581372519713ba817645d96acf4d633d069ffede03cec702dc7343605ff603b%2037866%20python-pysaml2-doc_2.0.0-1%2Bdeb8u1_all.deb%0A%3E%20Files%3A%0A">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=zigo%40debian.org" alt="">
<div class="header"><span class="headerfield">From:</span> Thomas Goirand &lt;zigo@debian.org&gt;</div>
<div class="header"><span class="headerfield">To:</span> 850716-close@bugs.debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Bug#850716: fixed in python-pysaml2 2.0.0-1+deb8u1</div>
<div class="header"><span class="headerfield">Date:</span> Sun, 15 Jan 2017 23:02:54 +0000</div>
</div>
<pre class="message">Source: python-pysaml2
Source-Version: 2.0.0-1+deb8u1

We believe that the bug you reported is fixed in the latest version of
python-pysaml2, which is due to be installed in the Debian FTP archive.

A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 850716@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Thomas Goirand &lt;zigo@debian.org&gt; (supplier of updated python-pysaml2 package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@ftp-master.debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Format: 1.8
Date: Mon, 09 Jan 2017 16:54:24 +0100
Source: python-pysaml2
Binary: python-pysaml2 python-pysaml2-doc
Architecture: source all
Version: 2.0.0-1+deb8u1
Distribution: jessie-security
Urgency: medium
Maintainer: PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;
Changed-By: Thomas Goirand &lt;zigo@debian.org&gt;
Description:
 python-pysaml2 - SAML Version 2 to be used in a WSGI environment - Python 2.x
 python-pysaml2-doc - SAML Version 2 to be used in a WSGI environment - doc
Closes: <a href="bugreport.cgi?bug=850716">850716</a>
Changes:
 python-pysaml2 (2.0.0-1+deb8u1) jessie-security; urgency=medium
 .
   * Fix XXE issues on anything where pysaml2 parses XML directly:
     - <a href="https://security-tracker.debian.org/tracker/CVE-2016-10127">CVE-2016-10127</a>: backporting upstream patch (Closes: #<a href="bugreport.cgi?bug=850716">850716</a>).
     - add python-defusedxml as runtime depends.
     - switch debian/gbp.conf to use debian/jessie as packaging branch.
   * Add python-pymongo as (build-)depends.
Checksums-Sha1:
 0bbf1194d95c45f1fdd9c20cfb5ced27812a404a 2383 python-pysaml2_2.0.0-1+deb8u1.dsc
 f1fe1d6a295686640b147519711577b328c9d17a 2615832 python-pysaml2_2.0.0.orig.tar.xz
 fe368731d7f97ebbb0be245d1320ae52137e399c 5944 python-pysaml2_2.0.0-1+deb8u1.debian.tar.xz
 ff1a794513f23be464e3cc2f5badf82ee46a0259 176868 python-pysaml2_2.0.0-1+deb8u1_all.deb
 25b6b3d497909f8b68d300dd939b4621ae0618ea 37866 python-pysaml2-doc_2.0.0-1+deb8u1_all.deb
Checksums-Sha256:
 651009543559ba6fff0dc051bb717f69f717255a9eaa259dc57584f6dcbcee50 2383 python-pysaml2_2.0.0-1+deb8u1.dsc
 c62d179ba27d345d9159d9a3f2bddea7567973720cbf916bbd05eda3e18e935f 2615832 python-pysaml2_2.0.0.orig.tar.xz
 78209ca2e4ee6c6fd00a0c735646f668f1e5d0187d98c120c49a821ac20375c7 5944 python-pysaml2_2.0.0-1+deb8u1.debian.tar.xz
 3e85114f08d18f3c64ca2b9d6703de44c2655298c6262701665ad1790f47784a 176868 python-pysaml2_2.0.0-1+deb8u1_all.deb
 b581372519713ba817645d96acf4d633d069ffede03cec702dc7343605ff603b 37866 python-pysaml2-doc_2.0.0-1+deb8u1_all.deb
Files:
 0a21478383a7f075b00477cdf3007aa2 2383 python optional python-pysaml2_2.0.0-1+deb8u1.dsc
 ff545022ba4ba6bbfe27e020001b9eb0 2615832 python optional python-pysaml2_2.0.0.orig.tar.xz
 43077bb4c9864f93b2db54252154294f 5944 python optional python-pysaml2_2.0.0-1+deb8u1.debian.tar.xz
 efbc1b2f04f03a08ff6fa9b9ce49e912 176868 python optional python-pysaml2_2.0.0-1+deb8u1_all.deb
 80dc4fae343c8c5bf34b9b9f39083674 37866 doc optional python-pysaml2-doc_2.0.0-1+deb8u1_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBCAAGBQJYdnRoAAoJENQWrRWsa0P+1OQQAInAMrUW7KScS+RLQ5U9Z0oL
6sTmRSlZ7tcumrRtMgXW7dKguwCEKFf+vL2JEQ1LNkt7KcjwYunPfywphhaE1Qlm
YVWfXfC7A4cU3xAw12Q7FGkWhW2fSF23AlsllFrqjFJ331SvfWZ3i9PGLrzSUoE6
vT5+Pf9aL1P5srZXxRNpZpHFvWUaHOzpgO/Lk3SnZbVIrPTihdRmqSWl23J10iZQ
9hjnOx25tEAtb6dcHlPZaRaxZEnKOVWVh0GCRlkRvB41mo7ClwFnJ6S5J+DsmxpA
QufF0INkr0p4rXaFFJs7SHabV6/URTdCkBGjbcYdJAxx4bT1krM0FNnir4UcIwJ6
mpOLjOyR6+L0c5dJkCU+yAunKX4n1AklvOd/f//FauoEBPFghz5dRM29nZPo9eCD
deKCA/gdRXrFS/IzzpmP8dJ6rXfAb+4p4HnEiL8WVv3/2jxTOUDz+EZuK5nxsDPX
KSmlD9ihpVvqriQeRWsiRAiM4pp5SQHR6ftws85rVBg1FJ6Fut+YPYJDncxSYPNy
5+JKMRM9Tvf39uXGmeAdusF/ekysUgQKuxxY5GM0kwde5lm6GHUv6aL6UpHQ9IXo
JqcTOzjtzpsZa7bDc7fj09dzCsVq+blExvm2KD1sGkxrLaL2q17eAdHjv7aBbHS1
R2cVRsYLa01JLcrdZQXu
=ivso
-----END PGP SIGNATURE-----



</pre>

<div class="msgreceived"><hr><p>
<a name="29"></a>
<!-- command:title -->
<!-- requester: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- request_addr: control@bugs.debian.org -->
<!-- time:1484851144 -->
<!-- new_data:
$new_data = {
              &#39;subject&#39; =&gt; &#39;python-pysaml2: CVE-2016-10149&#39;
            };
-->
<!-- old_data:
$old_data = {
              &#39;subject&#39; =&gt; &#39;python-pysaml2: CVE-2016-10127: XML External Entity attack&#39;
            };
-->
<strong>Changed Bug title to &#39;python-pysaml2: CVE-2016-10149&#39; from &#39;python-pysaml2: CVE-2016-10127: XML External Entity attack&#39;.</strong>
Request was from <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>
to <code>control@bugs.debian.org</code>.
 (Thu, 19 Jan 2017 18:39:04 GMT) (<a href="bugreport.cgi?bug=850716;msg=30">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=30">mbox</a>, <a href="#29">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="31"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt; -->
<!-- time:1484852762 -->
<strong>Information forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>:<br>
<code>Bug#850716</code>; Package <code>src:python-pysaml2</code>.
 (Thu, 19 Jan 2017 19:06:02 GMT) (<a href="bugreport.cgi?bug=850716;msg=32">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=32">mbox</a>, <a href="#31">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="33"></a>
<!-- request_addr: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- time:1484852762 -->
<strong>Acknowledgement sent</strong>
to <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>:<br>
Extra info received and forwarded to list.  Copy sent to <code>PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>.
 (Thu, 19 Jan 2017 19:06:02 GMT) (<a href="bugreport.cgi?bug=850716;msg=34">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=34">mbox</a>, <a href="#33">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="35"></a><a name="msg35"></a><a href="#35">Message #35</a> received at 850716@bugs.debian.org (<a href="bugreport.cgi?bug=850716;msg=35">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=35">mbox</a>, <a href="mailto:850716@bugs.debian.org?References=%3C20170109152840.16451.84741.reportbug%40buzig2.mirantis.com%3E%0A%20%3C20170119190209.bvo2dgswqtjgd5xp%40eldamar.local%3E&amp;body=On%20Thu%2C%2019%20Jan%202017%2020%3A02%3A09%20%2B0100%20Salvatore%20Bonaccorso%20%3Ccarnil%40debian.org%3E%20wrote%3A%0A%3E%20Hi%2C%0A%3E%20%0A%3E%20On%20Mon%2C%20Jan%2009%2C%202017%20at%2004%3A28%3A40PM%20%2B0100%2C%20Thomas%20Goirand%20wrote%3A%0A%3E%20%3E%20there%20was%20a%20security%20hole%20fixed%20in%20python-pysaml2%2C%20which%20allowed%20XML%0A%3E%20%3E%20External%20Entity%20attacks%3A%0A%3E%20%3E%20https%3A%2F%2Fgithub.com%2Frohe%2Fpysaml2%2Fpull%2F379%0A%3E%20%3E%20https%3A%2F%2Fgithub.com%2Frohe%2Fpysaml2%2Fcommit%2F6e09a25d9b4b7aa7a506853210a9a14100b8bc9b%0A%3E%20%0A%3E%20Apparently%20there%20was%20some%20confusion.%20To%20be%20clear%2C%20the%20above%20commit%20now%0A%3E%20after%20re-clarification%20from%20MITRE%20is%20CVE-2016-10149%5B1%5D%2C%20which%20means%0A%3E%20the%20initially%20assigned%20CVE%20for%20the%20XXE%20vulnerability%20in%20pysaml2%20is%0A%3E%20still%20unfixed.%20Will%20open%20another%20bug%20for%20it.%20See%20the%20comments%20in%20the%0A%3E%20references%20oss-security%20post%20for%20details.%0A%3E%20%0A%3E%20%20%5B1%5D%20https%3A%2F%2Fmarc.info%2F%3Fl%3Doss-security%26m%3D148484731923389%26w%3D2%0A%3E%20%0A%3E%20Regards%2C%0A%3E%20Salvatore%0A%3E%20%0A%3E%20%0A&amp;subject=Re%3A%20Bug%23850716%3A%20XML%20External%20Entity%20attack&amp;In-Reply-To=%3C20170119190209.bvo2dgswqtjgd5xp%40eldamar.local%3E">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=carnil%40debian.org" alt="">
<div class="header"><span class="headerfield">From:</span> Salvatore Bonaccorso &lt;carnil@debian.org&gt;</div>
<div class="header"><span class="headerfield">To:</span> Thomas Goirand &lt;zigo@debian.org&gt;, 850716@bugs.debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Re: Bug#850716: XML External Entity attack</div>
<div class="header"><span class="headerfield">Date:</span> Thu, 19 Jan 2017 20:02:09 +0100</div>
</div>
<pre class="message">Hi,

On Mon, Jan 09, 2017 at 04:28:40PM +0100, Thomas Goirand wrote:
&gt; there was a security hole fixed in python-pysaml2, which allowed XML
&gt; External Entity attacks:
&gt; <a href="https://github.com/rohe/pysaml2/pull/379">https://github.com/rohe/pysaml2/pull/379</a>
&gt; <a href="https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b">https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b</a>

Apparently there was some confusion. To be clear, the above commit now
after re-clarification from MITRE is <a href="https://security-tracker.debian.org/tracker/CVE-2016-10149">CVE-2016-10149</a>[1], which means
the initially assigned CVE for the XXE vulnerability in pysaml2 is
still unfixed. Will open another bug for it. See the comments in the
references oss-security post for details.

 [1] <a href="https://marc.info/?l=oss-security&amp;m=148484731923389&amp;w=2">https://marc.info/?l=oss-security&amp;m=148484731923389&amp;w=2</a>

Regards,
Salvatore


</pre>

<div class="infmessage"><hr><p>
<a name="36"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt; -->
<!-- time:1484906762 -->
<strong>Information forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>:<br>
<code>Bug#850716</code>; Package <code>src:python-pysaml2</code>.
 (Fri, 20 Jan 2017 10:06:02 GMT) (<a href="bugreport.cgi?bug=850716;msg=37">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=37">mbox</a>, <a href="#36">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="38"></a>
<!-- request_addr: Thomas Goirand &lt;zigo@debian.org&gt; -->
<!-- time:1484906762 -->
<strong>Acknowledgement sent</strong>
to <code>Thomas Goirand &lt;zigo@debian.org&gt;</code>:<br>
Extra info received and forwarded to list.  Copy sent to <code>PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>.
 (Fri, 20 Jan 2017 10:06:02 GMT) (<a href="bugreport.cgi?bug=850716;msg=39">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=39">mbox</a>, <a href="#38">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="40"></a><a name="msg40"></a><a href="#40">Message #40</a> received at 850716@bugs.debian.org (<a href="bugreport.cgi?bug=850716;msg=40">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=40">mbox</a>, <a href="mailto:850716@bugs.debian.org?In-Reply-To=%3C7ae77cf9-338a-9e40-b46f-0ede0a110288%40debian.org%3E&amp;body=On%20Fri%2C%2020%20Jan%202017%2011%3A02%3A56%20%2B0100%20Thomas%20Goirand%20%3Czigo%40debian.org%3E%20wrote%3A%0A%3E%20On%2001%2F19%2F2017%2008%3A02%20PM%2C%20Salvatore%20Bonaccorso%20wrote%3A%0A%3E%20%3E%20Hi%2C%0A%3E%20%3E%20%0A%3E%20%3E%20On%20Mon%2C%20Jan%2009%2C%202017%20at%2004%3A28%3A40PM%20%2B0100%2C%20Thomas%20Goirand%20wrote%3A%0A%3E%20%3E%3E%20there%20was%20a%20security%20hole%20fixed%20in%20python-pysaml2%2C%20which%20allowed%20XML%0A%3E%20%3E%3E%20External%20Entity%20attacks%3A%0A%3E%20%3E%3E%20https%3A%2F%2Fgithub.com%2Frohe%2Fpysaml2%2Fpull%2F379%0A%3E%20%3E%3E%20https%3A%2F%2Fgithub.com%2Frohe%2Fpysaml2%2Fcommit%2F6e09a25d9b4b7aa7a506853210a9a14100b8bc9b%0A%3E%20%3E%20%0A%3E%20%3E%20Apparently%20there%20was%20some%20confusion.%20To%20be%20clear%2C%20the%20above%20commit%20now%0A%3E%20%3E%20after%20re-clarification%20from%20MITRE%20is%20CVE-2016-10149%5B1%5D%2C%20which%20means%0A%3E%20%3E%20the%20initially%20assigned%20CVE%20for%20the%20XXE%20vulnerability%20in%20pysaml2%20is%0A%3E%20%3E%20still%20unfixed.%20Will%20open%20another%20bug%20for%20it.%20See%20the%20comments%20in%20the%0A%3E%20%3E%20references%20oss-security%20post%20for%20details.%0A%3E%20%3E%20%0A%3E%20%3E%20%20%5B1%5D%20https%3A%2F%2Fmarc.info%2F%3Fl%3Doss-security%26m%3D148484731923389%26w%3D2%0A%3E%20%3E%20%0A%3E%20%3E%20Regards%2C%0A%3E%20%3E%20Salvatore%0A%3E%20%0A%3E%20Is%20there%20a%20new%20patch%20available%3F%0A%3E%20%0A%3E%20Cheers%2C%0A%3E%20%0A%3E%20Thomas%20Goirand%20%28zigo%29%0A%3E%20%0A%3E%20%0A%3E%20%0A&amp;References=%3C20170109152840.16451.84741.reportbug%40buzig2.mirantis.com%3E%0A%20%3C20170119190209.bvo2dgswqtjgd5xp%40eldamar.local%3E%0A%20%3C7ae77cf9-338a-9e40-b46f-0ede0a110288%40debian.org%3E&amp;subject=Re%3A%20%5BPKG-Openstack-devel%5D%20Bug%23850716%3A%20XML%20External%20Entity%20attack">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=zigo%40debian.org" alt="">
<div class="header"><span class="headerfield">From:</span> Thomas Goirand &lt;zigo@debian.org&gt;</div>
<div class="header"><span class="headerfield">To:</span> 850716@bugs.debian.org, Salvatore Bonaccorso &lt;carnil@debian.org&gt;,
 security@debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Re: [PKG-Openstack-devel] Bug#850716: XML External Entity attack</div>
<div class="header"><span class="headerfield">Date:</span> Fri, 20 Jan 2017 11:02:56 +0100</div>
</div>
<pre class="message">On 01/19/2017 08:02 PM, Salvatore Bonaccorso wrote:
&gt; Hi,
&gt; 
&gt; On Mon, Jan 09, 2017 at 04:28:40PM +0100, Thomas Goirand wrote:
&gt;&gt; there was a security hole fixed in python-pysaml2, which allowed XML
&gt;&gt; External Entity attacks:
&gt;&gt; <a href="https://github.com/rohe/pysaml2/pull/379">https://github.com/rohe/pysaml2/pull/379</a>
&gt;&gt; <a href="https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b">https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b</a>
&gt; 
&gt; Apparently there was some confusion. To be clear, the above commit now
&gt; after re-clarification from MITRE is <a href="https://security-tracker.debian.org/tracker/CVE-2016-10149">CVE-2016-10149</a>[1], which means
&gt; the initially assigned CVE for the XXE vulnerability in pysaml2 is
&gt; still unfixed. Will open another bug for it. See the comments in the
&gt; references oss-security post for details.
&gt; 
&gt;  [1] <a href="https://marc.info/?l=oss-security&amp;m=148484731923389&amp;w=2">https://marc.info/?l=oss-security&amp;m=148484731923389&amp;w=2</a>
&gt; 
&gt; Regards,
&gt; Salvatore

Is there a new patch available?

Cheers,

Thomas Goirand (zigo)



</pre>

<div class="infmessage"><hr><p>
<a name="41"></a>
<!-- request_addr: debian-bugs-dist@lists.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt; -->
<!-- time:1484940788 -->
<strong>Information forwarded</strong>
to <code>debian-bugs-dist@lists.debian.org, PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>:<br>
<code>Bug#850716</code>; Package <code>src:python-pysaml2</code>.
 (Fri, 20 Jan 2017 19:33:08 GMT) (<a href="bugreport.cgi?bug=850716;msg=42">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=42">mbox</a>, <a href="#41">link</a>).</p></p></div>

<div class="infmessage"><hr><p>
<a name="43"></a>
<!-- request_addr: Salvatore Bonaccorso &lt;carnil@debian.org&gt; -->
<!-- time:1484940788 -->
<strong>Acknowledgement sent</strong>
to <code>Salvatore Bonaccorso &lt;carnil@debian.org&gt;</code>:<br>
Extra info received and forwarded to list.  Copy sent to <code>PKG OpenStack &lt;openstack-devel@lists.alioth.debian.org&gt;</code>.
 (Fri, 20 Jan 2017 19:33:08 GMT) (<a href="bugreport.cgi?bug=850716;msg=44">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=44">mbox</a>, <a href="#43">link</a>).</p></p></div>

<hr><p class="msgreceived"><a name="45"></a><a name="msg45"></a><a href="#45">Message #45</a> received at 850716@bugs.debian.org (<a href="bugreport.cgi?bug=850716;msg=45">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=45">mbox</a>, <a href="mailto:850716@bugs.debian.org?body=On%20Fri%2C%2020%20Jan%202017%2020%3A28%3A46%20%2B0100%20Salvatore%20Bonaccorso%20%3Ccarnil%40debian.org%3E%20wrote%3A%0A%3E%20Hi%20Thomas%2C%0A%3E%20%0A%3E%20On%20Fri%2C%20Jan%2020%2C%202017%20at%2011%3A02%3A56AM%20%2B0100%2C%20Thomas%20Goirand%20wrote%3A%0A%3E%20%3E%20On%2001%2F19%2F2017%2008%3A02%20PM%2C%20Salvatore%20Bonaccorso%20wrote%3A%0A%3E%20%3E%20%3E%20Hi%2C%0A%3E%20%3E%20%3E%20%0A%3E%20%3E%20%3E%20On%20Mon%2C%20Jan%2009%2C%202017%20at%2004%3A28%3A40PM%20%2B0100%2C%20Thomas%20Goirand%20wrote%3A%0A%3E%20%3E%20%3E%3E%20there%20was%20a%20security%20hole%20fixed%20in%20python-pysaml2%2C%20which%20allowed%20XML%0A%3E%20%3E%20%3E%3E%20External%20Entity%20attacks%3A%0A%3E%20%3E%20%3E%3E%20https%3A%2F%2Fgithub.com%2Frohe%2Fpysaml2%2Fpull%2F379%0A%3E%20%3E%20%3E%3E%20https%3A%2F%2Fgithub.com%2Frohe%2Fpysaml2%2Fcommit%2F6e09a25d9b4b7aa7a506853210a9a14100b8bc9b%0A%3E%20%3E%20%3E%20%0A%3E%20%3E%20%3E%20Apparently%20there%20was%20some%20confusion.%20To%20be%20clear%2C%20the%20above%20commit%20now%0A%3E%20%3E%20%3E%20after%20re-clarification%20from%20MITRE%20is%20CVE-2016-10149%5B1%5D%2C%20which%20means%0A%3E%20%3E%20%3E%20the%20initially%20assigned%20CVE%20for%20the%20XXE%20vulnerability%20in%20pysaml2%20is%0A%3E%20%3E%20%3E%20still%20unfixed.%20Will%20open%20another%20bug%20for%20it.%20See%20the%20comments%20in%20the%0A%3E%20%3E%20%3E%20references%20oss-security%20post%20for%20details.%0A%3E%20%3E%20%3E%20%0A%3E%20%3E%20%3E%20%20%5B1%5D%20https%3A%2F%2Fmarc.info%2F%3Fl%3Doss-security%26m%3D148484731923389%26w%3D2%0A%3E%20%3E%20%3E%20%0A%3E%20%3E%20%3E%20Regards%2C%0A%3E%20%3E%20%3E%20Salvatore%0A%3E%20%3E%20%0A%3E%20%3E%20Is%20there%20a%20new%20patch%20available%3F%0A%3E%20%0A%3E%20No%2C%20TTBOMK%2C%20there%20is%20no%20fix%20yet%20for%20that.%0A%3E%20%0A%3E%20Regards%2C%0A%3E%20Salvatore%0A%3E%20%0A%3E%20%0A&amp;References=%3C20170109152840.16451.84741.reportbug%40buzig2.mirantis.com%3E%0A%20%3C20170119190209.bvo2dgswqtjgd5xp%40eldamar.local%3E%0A%20%3C7ae77cf9-338a-9e40-b46f-0ede0a110288%40debian.org%3E%0A%20%3C20170120192846.7j75cw27oieucyie%40eldamar.local%3E&amp;subject=Re%3A%20Bug%23850716%3A%20%5BPKG-Openstack-devel%5D%20Bug%23850716%3A%20XML%20External%0A%20Entity%20attack&amp;In-Reply-To=%3C20170120192846.7j75cw27oieucyie%40eldamar.local%3E">reply</a>):</p>
<div class="headers">
<img src="/cgi-bin/libravatar.cgi?email=carnil%40debian.org" alt="">
<div class="header"><span class="headerfield">From:</span> Salvatore Bonaccorso &lt;carnil@debian.org&gt;</div>
<div class="header"><span class="headerfield">To:</span> Thomas Goirand &lt;zigo@debian.org&gt;, 850716@bugs.debian.org</div>
<div class="header"><span class="headerfield">Cc:</span> security@debian.org</div>
<div class="header"><span class="headerfield">Subject:</span> Re: Bug#850716: [PKG-Openstack-devel] Bug#850716: XML External
 Entity attack</div>
<div class="header"><span class="headerfield">Date:</span> Fri, 20 Jan 2017 20:28:46 +0100</div>
</div>
<pre class="message">Hi Thomas,

On Fri, Jan 20, 2017 at 11:02:56AM +0100, Thomas Goirand wrote:
&gt; On 01/19/2017 08:02 PM, Salvatore Bonaccorso wrote:
&gt; &gt; Hi,
&gt; &gt; 
&gt; &gt; On Mon, Jan 09, 2017 at 04:28:40PM +0100, Thomas Goirand wrote:
&gt; &gt;&gt; there was a security hole fixed in python-pysaml2, which allowed XML
&gt; &gt;&gt; External Entity attacks:
&gt; &gt;&gt; <a href="https://github.com/rohe/pysaml2/pull/379">https://github.com/rohe/pysaml2/pull/379</a>
&gt; &gt;&gt; <a href="https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b">https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b</a>
&gt; &gt; 
&gt; &gt; Apparently there was some confusion. To be clear, the above commit now
&gt; &gt; after re-clarification from MITRE is <a href="https://security-tracker.debian.org/tracker/CVE-2016-10149">CVE-2016-10149</a>[1], which means
&gt; &gt; the initially assigned CVE for the XXE vulnerability in pysaml2 is
&gt; &gt; still unfixed. Will open another bug for it. See the comments in the
&gt; &gt; references oss-security post for details.
&gt; &gt; 
&gt; &gt;  [1] <a href="https://marc.info/?l=oss-security&amp;m=148484731923389&amp;w=2">https://marc.info/?l=oss-security&amp;m=148484731923389&amp;w=2</a>
&gt; &gt; 
&gt; &gt; Regards,
&gt; &gt; Salvatore
&gt; 
&gt; Is there a new patch available?

No, TTBOMK, there is no fix yet for that.

Regards,
Salvatore


</pre>

<div class="msgreceived"><hr><p>
<a name="46"></a>
<!-- command:archive -->
<!-- requester: Debbugs Internal Request &lt;owner@bugs.debian.org&gt; -->
<!-- request_addr: internal_control@bugs.debian.org -->
<!-- time:1494141978 -->
<!-- new_data:
$new_data = {};
-->
<!-- old_data:
$old_data = {};
-->
<strong>Bug archived.</strong>
Request was from <code>Debbugs Internal Request &lt;owner@bugs.debian.org&gt;</code>
to <code>internal_control@bugs.debian.org</code>.
 (Sun, 07 May 2017 07:26:18 GMT) (<a href="bugreport.cgi?bug=850716;msg=47">full text</a>, <a href="bugreport.cgi?bug=850716;mbox=yes;msg=47">mbox</a>, <a href="#46">link</a>).</p></p></div>

<hr>
<p class="msgreceived">Send a report that <a href="https://bugs.debian.org/cgi-bin/bugspam.cgi?bug=850716">this bug log contains spam</a>.</p>
<hr>
<ADDRESS>Debian bug tracking system administrator &lt;<A HREF="mailto:owner@bugs.debian.org">owner@bugs.debian.org</A>&gt;.
Last modified:
<!--timestamp-->Sat Oct 30 18:33:05 2021<!--end timestamp-->; 
Machine Name:
<!--machinename-->buxtehude<!--machinename-->
<P>
<A HREF="https://www.debian.org/Bugs/">Debian Bug tracking system</A>
</p>
<p>
  Debbugs is free software and licensed under the terms of the GNU
  Public License version 2. The current version can be obtained
  from <a href="https://bugs.debian.org/debbugs-source/">https://bugs.debian.org/debbugs-source/</a>.
</p>
<p>
Copyright © 1999 Darren O. Benham,
1997,2003 nCipher Corporation Ltd,
1994-97 Ian Jackson,
2005-2017 Don Armstrong, and many other contributors.
</p>
</ADDRESS>

</body>
</html>
