{
    "error": "HTTPSConnectionPool(host='bugs.trustix.org', port=443): Max retries exceeded with url: /show_bug.cgi?id=1754 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52daefd520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}